App\Entity\Categoria:
  properties:
    categoria:
      - NotBlank:
          message: 'El campo Categoria es obligatorio'
      - Length:
          min: 2
          max: 100
          minMessage: 'Almenos 2 caracteres'
          maxMessage: 'MÃ¡ximo 100 caracteres'
      - Type: string